"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResultMessages = exports.ResultCodes = void 0;
var ResultCodes;
(function (ResultCodes) {
    ResultCodes["SUCCESS"] = "00000";
    ResultCodes["SUCCESS_GATEWAY"] = "00";
    ResultCodes["SUCCESS_GATEWAY_APPROVE"] = "APPROVED";
    ResultCodes["SUCCESS_GATEWAY_PREAUTH_APPROVE"] = "PREAUTH-APPROVED";
    ResultCodes["WARNING"] = "01000";
    ResultCodes["ERROR"] = "15000";
    ResultCodes["INVALID_PARAMETERS"] = "15400";
    ResultCodes["UNAUTHORIZED"] = "14010";
    ResultCodes["TOKEN_NOT_PRESENT"] = "14013";
    ResultCodes["INVALID_TOKEN"] = "14014";
})(ResultCodes = exports.ResultCodes || (exports.ResultCodes = {}));
var ResultMessages;
(function (ResultMessages) {
    ResultMessages["OK"] = "OK";
    ResultMessages["SUCCESS"] = "Operation performed successfully";
    ResultMessages["ERROR"] = "Internal Error";
    ResultMessages["UNAUTHORIZED"] = "Unauthorized";
    ResultMessages["NOT_FOUND"] = "Not found";
    ResultMessages["TOKEN_NOT_PRESENT"] = "Token not present";
    ResultMessages["INVALID_TOKEN"] = "Invalid Token";
    ResultMessages["TOKEN_EXPIRED"] = "Token expired";
    ResultMessages["DEACTIVE_TOKEN"] = "Token is not active";
    ResultMessages["LINK_EXPIRED"] = "Link is expired!";
    ResultMessages["NO_RECORD_FOUND"] = "No record found!";
    ResultMessages["NO_INVOICE_FOUND"] = "No invoice found!";
    ResultMessages["APPLICATION_NOT_FOUND"] = "Application not found!";
    ResultMessages["USER_NOT_FOUND"] = "User not found!";
    ResultMessages["USER_ALREADY_EXISTS"] = "User already exists!";
    ResultMessages["UNEXPECTED_GATEWAY_ERROR"] = "Occurred problem with Processing";
    ResultMessages["INVALID_CREDENTIALS"] = "Username or Password is incorrect";
})(ResultMessages = exports.ResultMessages || (exports.ResultMessages = {}));
